defaults:
  - base_gat
  - trainer: sgd

hidden_dims: [16]
# dropout: 0.8
dropout: 0.3
inplace: False
cached: True
name: gat
heads: 4

trainer:
  optimizer:
    lr: 1e-2
    weight_decay: 1e-4
  early_stopping:
    patience: 50
    save_model_state: True